Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
flood_output.plot(col="time", col_wrap=3)
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[33][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [43mflood_output[49m[43m.[49m[43mplot[49m[43m([49m[43mcol[49m[43m=[49m[33;43m"[39;49m[33;43mtime[39;49m[33;43m"[39;49m[43m,[49m[43m [49m[43mcol_wrap[49m[43m=[49m[32;43m3[39;49m[43m)[49m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/xarray/plot/accessor.py:48[39m, in [36mDataArrayPlotAccessor.__call__[39m[34m(self, **kwargs)[39m
[32m     46[39m [38;5;129m@functools[39m.wraps(dataarray_plot.plot, assigned=([33m"[39m[33m__doc__[39m[33m"[39m, [33m"[39m[33m__annotations__[39m[33m"[39m))
[32m     47[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__call__[39m([38;5;28mself[39m, **kwargs) -> Any:
[32m---> [39m[32m48[39m     [38;5;28;01mreturn[39;00m [43mdataarray_plot[49m[43m.[49m[43mplot[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43m_da[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/xarray/plot/dataarray_plot.py:310[39m, in [36mplot[39m[34m(darray, row, col, col_wrap, ax, hue, subplot_kws, **kwargs)[39m
[32m    306[39m     plotfunc = hist
[32m    308[39m kwargs[[33m"[39m[33max[39m[33m"[39m] = ax
[32m--> [39m[32m310[39m [38;5;28;01mreturn[39;00m [43mplotfunc[49m[43m([49m[43mdarray[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/xarray/plot/dataarray_plot.py:1507[39m, in [36m_plot2d.<locals>.newplotfunc[39m[34m(***failed resolving arguments***)[39m
[32m   1505[39m     [38;5;66;03m# Need the decorated plotting function[39;00m
[32m   1506[39m     allargs[[33m"[39m[33mplotfunc[39m[33m"[39m] = [38;5;28mglobals[39m()[plotfunc.[34m__name__[39m]
[32m-> [39m[32m1507[39m     [38;5;28;01mreturn[39;00m [43m_easy_facetgrid[49m[43m([49m[43mdarray[49m[43m,[49m[43m [49m[43mkind[49m[43m=[49m[33;43m"[39;49m[33;43mdataarray[39;49m[33;43m"[39;49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mallargs[49m[43m)[49m
[32m   1509[39m [38;5;28;01mif[39;00m darray.ndim == [32m0[39m [38;5;129;01mor[39;00m darray.size == [32m0[39m:
[32m   1510[39m     [38;5;66;03m# TypeError to be consistent with pandas[39;00m
[32m   1511[39m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([33m"[39m[33mNo numeric data to plot.[39m[33m"[39m)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/xarray/plot/facetgrid.py:1055[39m, in [36m_easy_facetgrid[39m[34m(data, plotfunc, kind, x, y, row, col, col_wrap, sharex, sharey, aspect, size, subplot_kws, ax, figsize, **kwargs)[39m
[32m   1052[39m     sharex = [38;5;28;01mFalse[39;00m
[32m   1053[39m     sharey = [38;5;28;01mFalse[39;00m
[32m-> [39m[32m1055[39m g = [43mFacetGrid[49m[43m([49m
[32m   1056[39m [43m    [49m[43mdata[49m[43m=[49m[43mdata[49m[43m,[49m
[32m   1057[39m [43m    [49m[43mcol[49m[43m=[49m[43mcol[49m[43m,[49m
[32m   1058[39m [43m    [49m[43mrow[49m[43m=[49m[43mrow[49m[43m,[49m
[32m   1059[39m [43m    [49m[43mcol_wrap[49m[43m=[49m[43mcol_wrap[49m[43m,[49m
[32m   1060[39m [43m    [49m[43msharex[49m[43m=[49m[43msharex[49m[43m,[49m
[32m   1061[39m [43m    [49m[43msharey[49m[43m=[49m[43msharey[49m[43m,[49m
[32m   1062[39m [43m    [49m[43mfigsize[49m[43m=[49m[43mfigsize[49m[43m,[49m
[32m   1063[39m [43m    [49m[43maspect[49m[43m=[49m[43maspect[49m[43m,[49m
[32m   1064[39m [43m    [49m[43msize[49m[43m=[49m[43msize[49m[43m,[49m
[32m   1065[39m [43m    [49m[43msubplot_kws[49m[43m=[49m[43msubplot_kws[49m[43m,[49m
[32m   1066[39m [43m[49m[43m)[49m
[32m   1068[39m [38;5;28;01mif[39;00m kind == [33m"[39m[33mline[39m[33m"[39m:
[32m   1069[39m     [38;5;28;01mreturn[39;00m g.map_dataarray_line(plotfunc, x, y, **kwargs)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/xarray/plot/facetgrid.py:169[39m, in [36mFacetGrid.__init__[39m[34m(self, data, col, row, col_wrap, sharex, sharey, figsize, aspect, size, subplot_kws)[39m
[32m    127[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__init__[39m(
[32m    128[39m     [38;5;28mself[39m,
[32m    129[39m     data: T_DataArrayOrSet,
[32m   (...)[39m[32m    138[39m     subplot_kws: [38;5;28mdict[39m[[38;5;28mstr[39m, Any] | [38;5;28;01mNone[39;00m = [38;5;28;01mNone[39;00m,
[32m    139[39m ) -> [38;5;28;01mNone[39;00m:
[32m    140[39m [38;5;250m    [39m[33;03m"""[39;00m
[32m    141[39m [33;03m    Parameters[39;00m
[32m    142[39m [33;03m    ----------[39;00m
[32m   (...)[39m[32m    166[39m 
[32m    167[39m [33;03m    """[39;00m
[32m--> [39m[32m169[39m     [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mmatplotlib[39;00m[34;01m.[39;00m[34;01mpyplot[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mplt[39;00m
[32m    171[39m     [38;5;66;03m# Handle corner case of nonunique coordinates[39;00m
[32m    172[39m     rep_col = col [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m data[col].to_index().is_unique

[31mModuleNotFoundError[39m: No module named 'matplotlib'

